name: Deploy Cloud Run Job
on:
  push:
    branches: ["main","hml","dev"]
jobs:
  cloud-run-job-deploy:
    uses: Matrix-Energia/matrix.data.pipelines/.github/workflows/gcp-cloud-run-job-build.yaml@latest
    with:
      dockerfile_path: 'Dockerfile'
      region: 'us-east1'
    secrets: inherit
